version: '3.8'
services:
  mysql-synapsys:
    image: gavassa/mysql-synapsys:v3
    container_name: mysql-synapsys
    environment:
      MYSQL_ROOT_PASSWORD: urubu100
      MYSQL_DATABASE: Synapsys
    ports:
      - "3306:3306"
    networks:
      - redeSynapsys
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d

  node-synapsys:
    image: gavassa/node-synapsys:v2
    container_name: node-synapsys
    build:
      context: ./projeto/Projeto-Synapsys
      dockerfile: Dockerfile
    environment:
      - DB_HOST:'172.18.0.1'
      - DB_DATABASE:'Synapsys'
      - DB_USER:'root'
      - DB_PASSWORD:'urubu100'
      - DB_PORT:3306
    ports:
      - "3333:3333"
    depends_on:
      - mysql-synapsys
    networks:
      - redeSynapsys

  java-synapsys:
    image: gavassa/java-synapsys:latest
    container_name: java-synapsys
    environment:
      DB_USER: root
      DB_PASSWORD: urubu100
      NAME_BUCKET: bucket-synapsys
      DB_URL: jdbc:mysql://172.18.0.2:3306/Synapsys
    depends_on:
      - mysql-synapsys
      - node-synapsys
    networks:
      - redeSynapsys
    command: ["java", "-jar", "java-project-synapsys-2.0-SNAPSHOT-jar-with-dependencies.jar"]

networks:
  redeSynapsys:
    driver: bridge
